In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
visa_df=pd.read_csv(r"C:\Users\Teja\Downloads\Visadataset - Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
num=visa_df.select_dtypes(exclude='object').columns
cat=visa_df.select_dtypes(include='object').columns

In [4]:
wine_df=pd.read_csv(r"C:\Users\Teja\OneDrive\Documents\NARESH IT\data_sets\winequality_red.csv")
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

 **Data science life cycle**

 
               data reading
                    |
               data cleaning
                    |
              data analysis
                   |
              featur engineering
                   |
             feature selection
                   |
             model dveelopment
                   |
            model evaluation
                   |
             model tuning
                   |
            model deployement

**featue engineering**
 - so far we have performed feature analysis
    -  data frame quick checks
    -  categorical column analysis
    -  bar charts,pie charts 
    -  numerical column analysis 
    -  histograms,box plots,outliers 
    -  bi-multi variant analysis
    -  correlation   etc
  
 -  now we need to learn feature engineering
    - we need to create a new column for better ml models
    - we need to perform **Encoding** ,which is convert catogorical to numerical data
    - we will do data **transformation**
    - we will perform **scaling: standardization and normalization**
    - we will perform the **missing values analysis**
- simply feature engineering means our data will be modified

**case_status**

In [8]:
# first we need to check how many unique labels are there
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [9]:
# create a dictonary
d={'Certified':0,'Denied':1}

In [10]:
# map the above dictonary with the original column
visa_df['case_status'].map(d)

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [11]:
# now we should change the original column with this column
visa_df['case_status']=visa_df['case_status'].map(d)

In [12]:
visa_df['case_status']

0        1
1        0
2        1
3        1
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: case_status, Length: 25480, dtype: int64

In [18]:
lables=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(lables)}
visa_df['education_of_employee'].map(d)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

- there are two types of encoders
    - label encoder
    - ordinal encoder

education               labelEncoder           OrdinalEncoder
==============================================================
high school                 1                        0
bachelor                    0                        1
masters                     2                        2
PH.D                        3                        3

here the normal order is 1,0,2,3====> ML model will see in this order   3>2>1>0
which indicates : PH.D>masters>hugh school>bachelor
 here we should give in the correct order for ml model

In [20]:
visa_df=pd.read_csv(r"C:\Users\Teja\Downloads\Visadataset - Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [ ]:
- sklearn : **Package**
    - preprocessing :  **module**
            - LabelEncoder: **class**
                 - fit_transform: **method**

import sklearn
sklearn.preprocessing

from sklearn import preprocessing
# and now we should import labelencoder   for this

# steps=  1 read the class
         # 2 save the class
         # 3 apply fit transform
from sklearn.preprocessing import LabelEncoder
le=labelEncoder()
le.fit_transform()

**fit transform**

    - fit: created a dictionary (find something)
    - transform: using above something we will modify the data

**LabelEncoder**

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [6]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])

In [9]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [10]:
visa_df=pd.read_csv(r"C:\Users\Teja\Downloads\Visadataset - Visadataset.csv")

In [15]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
for i in cat[1:]:    # dont consider caseID
    visa_df[i]=oe.fit_transform(visa_df[[i]])

In [17]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1.0,2.0,0.0,0.0,14513,2007,4.0,592.2029,0.0,1.0,1.0
1,EZYV02,1.0,3.0,1.0,0.0,2412,2002,2.0,83425.6500,3.0,1.0,0.0
2,EZYV03,1.0,0.0,0.0,1.0,44444,2008,4.0,122996.8600,3.0,1.0,1.0
3,EZYV04,1.0,0.0,0.0,0.0,98,1897,4.0,83434.0300,3.0,1.0,1.0
4,EZYV05,0.0,3.0,1.0,0.0,1082,2005,3.0,149907.3900,3.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1.0,0.0,1.0,1.0,2601,2008,3.0,77092.5700,3.0,1.0,0.0
25476,EZYV25477,1.0,2.0,1.0,0.0,3274,2006,2.0,279174.7900,3.0,1.0,0.0
25477,EZYV25478,1.0,3.0,1.0,0.0,1121,1910,3.0,146298.8500,3.0,0.0,0.0
25478,EZYV25479,1.0,3.0,1.0,1.0,1918,1887,4.0,86154.7700,3.0,1.0,0.0
25479,EZYV25480,1.0,0.0,1.0,0.0,3195,1960,1.0,70876.9100,3.0,1.0,0.0

In [18]:
visa_df=pd.read_csv(r"C:\Users\Teja\Downloads\Visadataset - Visadataset.csv")

**pd.get_dummies**

 - get dummies is a way to represent the catogorical columns to numerical
 - first it will check what are the labels in a column
 - for example casestatus has two labels
    - denied and certified
 - so it will create two new columns based on labels
    - col1: case_status_denied
    - col2: case_status_certified



case_status | case_status_Denied | case_status_Certified
 
Denied      |      1             |       0
 
Certified   |      0             |       1
  
Certified   |      0             |       1


 - **it is also called as one hot encoder**
 - it makes new columns are independent each other
 - some of ml algorithms expect that columns should be **independent** each other

In [19]:
pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]