**how to create null value in data**

In [2]:
import numpy as np
import pandas as pd

In [3]:
d={'names':['ramesh','suresh',None,'sathish'],
  'age':[None,22,24,25],
  'city':['hyd','blr','pune',None]}
df1=pd.DataFrame(d)
df1df1

     names   age  city
0   ramesh   NaN   hyd
1   suresh  22.0   blr
2     None  24.0  pune
3  sathish  25.0  None

In [9]:
df1.to_csv('data1.csv',index=False)

In [7]:
d={'names':['ramesh','suresh',np.nan,'sathish'],
  'age':[np.nan,22,24,25],
  'city':['hyd','blr','pune',np.nan]}
df2=pd.DataFrame(d)
df2

     names   age  city
0   ramesh   NaN   hyd
1   suresh  22.0   blr
2      NaN  24.0  pune
3  sathish  25.0   NaN

In [11]:
df2.to_csv('data2.csv',index=False)

 - categorical data use None
 - numerical data use np.nan

In [12]:
df1.isnull()
#is null()=wherever null value is there it will display as True

   names    age   city
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [13]:
df1.isnull().sum()

names    1
age      1
city     1
dtype: int64

In [15]:
df1.values

array([['ramesh', nan, 'hyd'],
       ['suresh', 22.0, 'blr'],
       [None, 24.0, 'pune'],
       ['sathish', 25.0, None]], dtype=object)

In [16]:
df1.dtypes

names     object
age      float64
city      object
dtype: object

**filling values**

In [19]:
# Random filling
df1.fillna(30)

     names   age  city
0   ramesh  30.0   hyd
1   suresh  22.0   blr
2       30  24.0  pune
3  sathish  25.0    30

In [20]:
#select 1 column and fill it with the value
df1['age'].fillna(30)

0    30.0
1    22.0
2    24.0
3    25.0
Name: age, dtype: float64

In [21]:
df1.fillna(method='pad')

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\3887010614.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

     names   age  city
0   ramesh   NaN   hyd
1   suresh  22.0   blr
2   suresh  24.0  pune
3  sathish  25.0  pune

In [22]:
df1.fillna(method='pad',axis=1)

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

     names     age  city
0   ramesh  ramesh   hyd
1   suresh    22.0   blr
2     None    24.0  pune
3  sathish    25.0  25.0

In [24]:
df1.fillna(method='bfill')

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

     names   age  city
0   ramesh  22.0   hyd
1   suresh  22.0   blr
2  sathish  24.0  pune
3  sathish  25.0  None

In [25]:
df1.fillna(method='bfill',axis=1)

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

     names   age  city
0   ramesh   hyd   hyd
1   suresh  22.0   blr
2     24.0  24.0  pune
3  sathish  25.0  None

In [26]:
df1.fillna(method='ffill')

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\598575452.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='ffill')

     names   age  city
0   ramesh   NaN   hyd
1   suresh  22.0   blr
2   suresh  24.0  pune
3  sathish  25.0  pune

In [27]:
df1.fillna(method='backfill')

C:\Users\Teja\AppData\Local\Temp\ipykernel_29084\2955370104.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='backfill')

     names   age  city
0   ramesh  22.0   hyd
1   suresh  22.0   blr
2  sathish  24.0  pune
3  sathish  25.0  None

In [29]:
df1['age'].fillna(df1['age'].mean())

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: age, dtype: float64

In [30]:
df1['age'].fillna(df1['age'].median())

0    24.0
1    22.0
2    24.0
3    25.0
Name: age, dtype: float64

- KNN : K-nearest neighbours
- where k is a number
- insted of taking avg of all the values data
    - first will find the neighbours who are close with missing data
    - by using euclidian distance calculation will identify the neighbours rows
    - suppose k=2 will identify two closeset rows
    - those closest row values will take it will calculate the mean
    - finally will fill with the mean

In [31]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(df1['names'])

ValueError: could not convert string to float: 'ramesh'